### ISSUE TITLE
스타트업 initialize할 때 어떤 도구들을 필요로 할까?

### ISSUE THREAD

**Issue by drakejin** [UniverseHan/startup-cli#1]
우선은 필요한 도구들을 나열해보고 가능한 정도를 보는것도 좋을것 같아요 !

**Comment by UniverseHan** [comment]
repository 만들기

**Comment by UniverseHan** [comment]
slack alarm

**Comment by drakejin** [comment]
gmail gsuite

**Comment by drakejin** [comment]
aws

**Comment by UniverseHan** [comment]
select default projects
- default project set(server, web-front, mobile). decide by our own mind because many very early startups may follow env which was built by previous developer...
- deselect one from projects set(becuase addition is more complex...)

**Comment by UniverseHan** [comment]
deploy when push to branch
- master branch to dev
- release branch to prod

**Comment by drakejin** [comment]
docker를 사용하게 하는게 나을까요?
클라우드 귀속적이지만 AWS를 쓰게 하는게 나을까요?
아니면 ..IDC를 기준으로..?
AWS 라면 serverless로 올려버리는걸 생각하고 있긴 한데..!

**Comment by UniverseHan** [comment]
> docker를 사용하게 하는게 나을까요?
> 클라우드 귀속적이지만 AWS를 쓰게 하는게 나을까요?
> 아니면 ..IDC를 기준으로..?

일단은 그냥 AWS EC2 정도로 하는게 어떨까요 서버는 기본은 EC2 입력하면 ECS혹은 점점 지원한다. 왜냐면 컨테이너가 좋긴 하지만 안써본 사람은 그냥 맨붕이니까... 아 하지만 로컬에서 똑같은 환경설정 제공하기에는 컨테이너가 좋긴한데.. 그렇게 되면 또 로컬 docker engine 설치 여부도 생기니.. 복잡해지는 ㅋㅋㅋ

뭐가 됐든 먼저 개발하는 사람이 편한 쪽으로 가되.. 불편하면 개선한다.

**Comment by UniverseHan** [comment]
provide document links for related components, for example
+ aws ec2 manual
+ github manual link
+ etc...

Becuase even it's hard to find where is the document I have to read.

**Comment by UniverseHan** [comment]
generate static manual page and open browser for it. it shows project architectural diagram

프로젝트어 어떻게 구성되었는지 쉽게 보여주려면 간단한 다이어그램으로 이런 구조를 가진 프로젝트 셋이 만들어 질거다 라는 그림이라도 보여주면 좋을것 같아요. 이게 텍스트 그림이어도 되고. 간단한 html페이지여도 되고.

**Comment by drakejin** [comment]
혹시 이런건 어때요? EC2에 AMI하나 커스터마이징해서 구운다음에
실제 cli가 인스턴스를 할때에 `aws ec2 create-instance`로 instance 실행시키는 타이밍에 셸스크립트를 실행 시킬 수 있거든요?

AMI 자체를 이미지가 인스턴스로 실행되는 순간에 가이드 대로의 셸 스크립트를 삽입하면 아래와 같은 작업을 수행하도록 해요.
1. gitlab의 group user들 ssh 키 인스턴스에 등록 [ssh접속을 위한]
2. gitlab repository의 소스코드를 가져와서 실행 [실행 소스코드는 circleCI나 gitlabCI에서 zip ball형태거나 뭐.. 등등]

**Comment by drakejin** [comment]
# AWS EC2 AMI의 동작 pseudo

#### 1번 example

``` bash
#!/bin/bash
set -e

# SSH Key 설정
key_path='/home/ec2-user/.ssh/authorized_keys'
users=($GITLAB_USERS)
for user in ${users[@]}; do
  curl -s https://gitlab.com/$user.keys >> $key_path
done
chown ec2-user:ec2-user $key_path
chmod 600 $key_path
```

#### 2번 example 은..  이런느낌으로..? 
``` bash
curl -so $REPO_URL/$REPO_RELEASE_VERSION $PROJECT_PATH
tar xvfz -f $PROJECT_PATH/{repo_name} .
cd $PROJECT_PATH
yarn start:prod
```

**Comment by UniverseHan** [comment]
오 좋네요 :)
